#import "imports.typ":*
== Basic idea of the detection

The measure and characterise the quadrature squeezing of the light field, we must be able to perform phase-sensitive measurements of the field operators:

$
hat(X_(theta)) = 1/2 (e^(-i theta) hat(a) + e^(i theta) hat(a^dagger))
$

Where $hat(a)$ is the signal mode's annihilation operator, and $theta$ is a tunable phase that decides the quadrature that is to be measured.

Two of the basic techniques that are used for the detection of the squeezed states that are discussed in the paper involve using a strong local oscillator (hereby referred to as LO) to procude a coherent state $ket(beta e^(i theta))$ with $beta >> 1$, and using it to perform a homodyne or a heterodyne measurement of the signal. this process involves the mixing of the singal moed with the LO mode using a 50/50 beam splitter, the action of which is represented by the following transformation:

$
mat(hat(c);hat(d)) = 1/(sqrt(a)) mat(1,1;1,-1) mat(hat(a);hat(b))
$

This yields the modes:

$
hat(c) = 1/(sqrt(2)) (hat(a) + hat(b))
$

$
hat(d) = 1/(sqrt(2)) (hat(a) - hat(b))
$

Where $hat(a)$ is the signal mode, and $hat(b)$ is the LO mode. The output modes are then detected using photodiodes, which essentially carry out a photon counting operation, i.e. $hat(c)^(dagger) hat(c)$ and $hat(d)^(dagger) d$.

== Homodyne detection
In this mode, the LO mode is prepared in the same frequency as the signal mode $omega$, and the phase $theta$ is varied. The difference in the photocurrent produced by the two photodiodes is given by:
$
hat(N_(-)) = hat(c)^(dagger) hat(c) - hat(d)^(dagger) hat(d) = hat(a)^(dagger) hat(b) + hat(b)^(dagger) hat(a)
$
In the strong LO approximation limit, $expval(hat(b)) = beta e^(- theta)$, and one can replace the $hat(b)$ operators with their expectation values. This yields:
$
hat(N_(-)) approx 2 |beta| hat(X_(theta))
$

Now, the variance in the photocurrent is given by:
$
V a r (hat(N_(-))) = 4 |beta|^2 expval((Delta hat(X_(theta)))^2)
$
If we observe a variance in the different photocurrent that is less than what is expected from a coherent state, i.e. $mod(beta)^2$, we can be sure that we are observing a squeezed state. The main benefit of this method is the direct access to all quadratures by modifying the phase of the LO mode, which we can alter from $theta=0$ to $theta = pi/2$ to access the two orthogonal quadratures. The disadvantage of this method is that the LO mode must be prepared in the same frequency as the signal mode, which is not always possible. This can be a problem in cases where the signal mode is at a different frequency, such as in the case of squeezed light generated by four-wave mixing or parametric down-conversion.

== Heterodyne detection
In this method, the LO mode is prepared in a slightly different frequency of $omega + delta omega$, and the phase $theta$ is varied. One of the output modes from the beamsplitter is given by:
$
hat(c)(t) = 1/(sqrt(2)) (hat(a) e^(- omega t) + beta e^(-i (omega + delta omega) t))
$
and the intensity of the photocurrent is given by:
$
hat(I)(t) = 1/2 [hat(a)^(dagger) hat(a) + |beta|^2 + beta^* hat(a) e^(-i delta omega t) + beta hat(a)^(dagger) e^(i delta omega t)]
$

Electronic filtering of the photocurrent is then done to remove the high frequency terms, and the resulting signal is given by:
$
hat(I_(b e a t))(t) = 1/2 [beta^* hat(a) e^(-i delta omega t) + beta hat(a)^(dagger) e^(i delta omega t)]
$

This contains information about both the quadrature amplitudes, as can be seen by substituting $beta = |beta| e^(i theta)$ to get;

$
hat(I_(b e a t))(t) = |beta| [hat(X_1) cos(delta omega t) + hat(X_2) sin(delta omega t)]
$

Demmodulation of this signal gives us the quadrature amplitudes, and thus the variances - and if we detect that any of them are less than the coherent state limit we can be sure that we have observed a squeezed state. The main advantage of this method is that the LO mode does not need to be prepared in the same frequency as the signal mode, which makes it more versatile. However, the disadvantage is that we do not have direct access to all quadratures, and we need to demodulate the signal to obtain the quadrature amplitudes.