#import "imports.typ":*

Before we move onto the core topic of our term paper report, we must give an introduction to what we squeezed states are. The time dependent electric field operator is some specififc polarization direction for one single mode is given by @Dirac1958:
$ E(t) = lambda (hat(a)e^(-i omega t) + hat(a)^dagger e^(i omega t)) $ where $lambda$ is a constant that contains information about the spatial wave functions. The operators $a, a^dagger$ obey boson commutation relations ($[a, a^dagger] = 1$). For more modes, we add up multiple different hilbert spaces of SHO, with different frequencies. We then write 
$ a = X_1 + i X_2 $ where we can see from the SHO equations, $X_1$ and $X_2$ are rescaled versions of the position and momentum operators, which obey the commutation relation $[X_1, X_2] = i/2$. We can then write the electric field operator as
$ E(t) = lambda/2 (X_1 cos(omega t) + X_2 sin(omega t)) $  where $X_1, X_2$ are the amplitudes of the two quadratures of the field. 

We use the generalized Heisenberg uncertainity principle to define the uncertainty in the two quadratures of the field. We can write the uncertainty in the two quadratures as
$ Delta X_1 Delta X_2 >= 1/4 $ where $Delta X_i = sqrt(expval(X_i^2) - expval(X_i)^2)$. 

We are interested in a states with minimum uncertainty. To do that we must have,
$Delta X_1 Delta X_2 = 1/4$. A class of these states are the states with $Delta X_1 = Delta X_2 = 1/2$ and $V(X_1) = V(X_2) = 1/4$, where $V(X)$ is the variance of the operator X. These are our coherent states, which are the eigenstates of the anhilation operator in the quantized electric field description. 

A larger class is by taking the variance in one quadrature to be lower than $1/4$ and the variance in the other quadrature to be more than that. These class of states are the called the squeezed states. We are interested in squeezed states which can be defined by the condition $V(X_i)<1/4$ where $i = 1$ or $2$.

We now see how these states are generated and what some of their mathematical properties are,
== Generating Squeezed States
We denote a coherent state as $ket(alpha)$. We know that a coherent state can be generated from the vaccuum state using the displacement operator $D(alpha)$,
$ ket(alpha) = D(alpha) ket(0) = exp(alpha a^dagger - alpha^* a) ket(0) $

A squeezed state $ket(alpha","zeta)$ can be generated by applying the squeezed operator and then the displacement operator on the ground state of the Simple Harmonic Oscillator.